-- 0009_exercise_media_bucket.sql
-- Aura Fitness — public read policy for the `exercise-media` Storage bucket.
--
-- WHY: exercise thumbnails currently point at arbitrary external hosts
-- (unsplash.com URLs baked into the bundled library JSON). Those can rot,
-- rate-limit, or disappear, and they leak a request to a third party on every
-- grid scroll. This bucket gives catalog imagery a first-party home, served
-- over plain HTTPS from the project's own CDN.
--
-- OWNER MANUAL STEP — RUN BEFORE THIS MIGRATION:
-- the bucket itself cannot be created from SQL. Create it PUBLIC, either:
--     supabase storage buckets create exercise-media --public
-- or Dashboard -> Storage -> New bucket -> name `exercise-media`, Public ON.
-- Applying this file without the bucket is harmless — the policy simply never
-- matches anything — but reads will 404 until it exists.
--
-- PATH CONVENTION (load-bearing, do not change):
--     exercise-media/{exercise_uuid}.jpg
-- The filename IS the join key: `{exercise_uuid}` is the deterministic UUIDv5
-- id from 0008_exercise_catalog.sql / supabase/seed/generate_seed.py. No DB
-- column records the image — a catalog row's `payload.imageURL` is written by
-- the seed generator from that same id, so the two cannot drift.
--
-- PUBLIC MEANS PUBLIC — the read policy below is unconditional for this
-- bucket: no auth, no uid check, anyone with the URL gets the bytes. NEVER put
-- user content here. `progress-photos` (0006) is the owner-only bucket and
-- stays that way; phase3-02's delete-account function deliberately keeps
-- `exercise-media` out of its USER_BUCKETS purge list (see the comment in
-- supabase/functions/delete-account/index.ts) because a shared bucket wiped on
-- one account's deletion would destroy every other user's imagery.
--
-- WRITE POSTURE — service role only. There is deliberately NO insert, update
-- or delete policy here. `storage.objects` has RLS enabled by Supabase, so an
-- anon or authenticated caller's upload is rejected (403 / 42501) simply by
-- finding no permitting policy. Seeding runs through the CLI with the service
-- role, which bypasses RLS: see supabase/seed/upload_media.sh, generated by
-- supabase/seed/generate_seed.py.
--
-- Re-runnable: the policy is dropped before being recreated.
--
-- Run via `supabase db push` (project must be linked with `supabase link`
-- first), or paste this file's contents into the Supabase Dashboard SQL editor
-- and run once.

-- MARK: - Unauthenticated read of exercise-media objects
--
-- SELECT only, and only for this bucket_id. Storage checks SELECT on download,
-- so this single policy is the whole read path; the absence of the other three
-- verbs is what locks writing down.

drop policy if exists "exercise_media_public_read" on storage.objects;
create policy "exercise_media_public_read" on storage.objects
  for select
  using (bucket_id = 'exercise-media');

-- VERIFY the write lockdown after applying (expect failure, not success):
--     supabase storage cp ./anything.jpg ss:///exercise-media/probe.jpg
-- run with the ANON key configured — it must fail with 403 "new row violates
-- row-level security policy". If it succeeds, a write policy leaked in from
-- somewhere else and every user can overwrite the catalog's imagery.
